// Isometry v5 — Phase 3 Worker Protocol Types
// Defines the typed message envelope system for main thread ↔ worker communication.
//
// Design principles:
//   - All payloads reference v0.1 types (no duplication)
//   - WorkerRequestType union enables exhaustive switch in router
//   - Correlation IDs enable concurrent request handling
//   - WorkerError provides structured error propagation (WKBR-03)

import type {
  Card,
  CardInput,
  CardListOptions,
  CardType,
  Connection,
  ConnectionInput,
  ConnectionDirection,
  SearchResult,
  CardWithDepth,
} from '../database/queries/types';

// Re-export types that consumers of WorkerBridge will need
export type {
  Card,
  CardInput,
  CardListOptions,
  CardType,
  Connection,
  ConnectionInput,
  ConnectionDirection,
  SearchResult,
  CardWithDepth,
};

// ---------------------------------------------------------------------------
// Request Types
// ---------------------------------------------------------------------------

/**
 * All possible request types. Each maps to a handler function signature.
 * This union becomes the exhaustive switch in the worker router.
 *
 * Naming convention: `domain:action`
 *   - card:create, card:get, card:update, card:delete, card:undelete, card:list
 *   - connection:create, connection:get, connection:delete
 *   - search:cards
 *   - graph:connected, graph:shortestPath
 *   - db:export
 */
export type WorkerRequestType =
  // Cards (CARD-01..06)
  | 'card:create'
  | 'card:get'
  | 'card:update'
  | 'card:delete'
  | 'card:undelete'
  | 'card:list'
  // Connections (CONN-01..04)
  | 'connection:create'
  | 'connection:get'
  | 'connection:delete'
  // Search (SRCH-01..04)
  | 'search:cards'
  // Graph (PERF-04)
  | 'graph:connected'
  | 'graph:shortestPath'
  // Database operations
  | 'db:export';

/**
 * Payload type map — keys are WorkerRequestType, values are payload shapes.
 * Each payload is a plain object that can cross the structuredClone boundary.
 */
export interface WorkerPayloads {
  // Cards
  'card:create': { input: CardInput };
  'card:get': { id: string };
  'card:update': { id: string; updates: Partial<Omit<CardInput, 'card_type'>> };
  'card:delete': { id: string };
  'card:undelete': { id: string };
  'card:list': { options?: CardListOptions };

  // Connections
  'connection:create': { input: ConnectionInput };
  'connection:get': { cardId: string; direction?: ConnectionDirection };
  'connection:delete': { id: string };

  // Search
  'search:cards': { query: string; limit?: number };

  // Graph
  'graph:connected': { startId: string; maxDepth?: number };
  'graph:shortestPath': { fromId: string; toId: string };

  // Database
  'db:export': Record<string, never>; // Empty object — no payload needed
}

/**
 * Response type map — keys are WorkerRequestType, values are response data shapes.
 * These are the `data` field contents when `success === true`.
 */
export interface WorkerResponses {
  'card:create': Card;
  'card:get': Card | null;
  'card:update': void;
  'card:delete': void;
  'card:undelete': void;
  'card:list': Card[];

  'connection:create': Connection;
  'connection:get': Connection[];
  'connection:delete': void;

  'search:cards': SearchResult[];

  'graph:connected': CardWithDepth[];
  'graph:shortestPath': string[] | null;

  'db:export': Uint8Array;
}

// ---------------------------------------------------------------------------
// Message Envelopes
// ---------------------------------------------------------------------------

/**
 * Request envelope sent from main thread to worker.
 *
 * @template T - The request type (must be a valid WorkerRequestType)
 *
 * The `id` field is a UUID correlation ID generated by WorkerBridge.
 * The worker echoes this ID in its response for promise resolution.
 */
export interface WorkerRequest<T extends WorkerRequestType = WorkerRequestType> {
  /** UUID correlation ID — used to match response to originating promise */
  id: string;
  /** Request type — determines which handler processes the message */
  type: T;
  /** Payload shape depends on type — see WorkerPayloads */
  payload: WorkerPayloads[T];
}

/**
 * Response envelope sent from worker to main thread.
 *
 * @template T - The response data type (inferred from request type)
 *
 * Either `success === true` with `data`, or `success === false` with `error`.
 * Never both, never neither.
 */
export interface WorkerResponse<T = unknown> {
  /** Matches the request.id that triggered this response */
  id: string;
  /** True if handler completed without throwing */
  success: boolean;
  /** Result data — present only when success === true */
  data?: T | undefined;
  /** Error info — present only when success === false */
  error?: WorkerError | undefined;
}

/**
 * Success response helper type — narrows WorkerResponse to success case.
 */
export interface WorkerSuccessResponse<T> {
  id: string;
  success: true;
  data: T;
  error?: undefined | WorkerError;
}

/**
 * Error response helper type — narrows WorkerResponse to error case.
 */
export interface WorkerErrorResponse {
  id: string;
  success: false;
  data?: undefined | unknown;
  error: WorkerError;
}

// ---------------------------------------------------------------------------
// Error Types
// ---------------------------------------------------------------------------

/**
 * Structured error for WKBR-03 compliance.
 * Provides machine-readable code and human-readable message.
 */
export interface WorkerError {
  /** Error classification code — enables programmatic error handling */
  code: WorkerErrorCode;
  /** Human-readable message (typically from Error.message) */
  message: string;
  /** Original stack trace — included only in development builds */
  stack?: string | undefined;
}

/**
 * Error codes for categorizing worker failures.
 *
 * UNKNOWN           - Catch-all for unexpected errors
 * NOT_INITIALIZED   - Operation attempted before database ready
 * INVALID_REQUEST   - Malformed request or unknown type
 * NOT_FOUND         - Requested entity does not exist
 * CONSTRAINT_VIOLATION - FK, unique, or check constraint failed
 * TIMEOUT           - Request exceeded time limit (set by WorkerBridge)
 */
export type WorkerErrorCode =
  | 'UNKNOWN'
  | 'NOT_INITIALIZED'
  | 'INVALID_REQUEST'
  | 'NOT_FOUND'
  | 'CONSTRAINT_VIOLATION'
  | 'TIMEOUT';

// ---------------------------------------------------------------------------
// Initialization Messages
// ---------------------------------------------------------------------------

/**
 * Special message posted by worker when initialization completes.
 * WorkerBridge awaits this before resolving `isReady`.
 */
export interface WorkerReadyMessage {
  type: 'ready';
  /** Timestamp when worker became ready (for latency tracking) */
  timestamp: number;
}

/**
 * Special message posted by worker if initialization fails.
 * WorkerBridge should reject `isReady` and surface the error.
 */
export interface WorkerInitErrorMessage {
  type: 'init-error';
  error: WorkerError;
}

/**
 * Union of all possible messages the worker can post.
 * Used for type narrowing in WorkerBridge's onmessage handler.
 */
export type WorkerMessage =
  | WorkerReadyMessage
  | WorkerInitErrorMessage
  | WorkerResponse;

// ---------------------------------------------------------------------------
// Type Guards
// ---------------------------------------------------------------------------

/**
 * Type guard to check if a message is the ready signal.
 */
export function isReadyMessage(msg: unknown): msg is WorkerReadyMessage {
  return (
    typeof msg === 'object' &&
    msg !== null &&
    'type' in msg &&
    (msg as WorkerReadyMessage).type === 'ready'
  );
}

/**
 * Type guard to check if a message is an init error.
 */
export function isInitErrorMessage(msg: unknown): msg is WorkerInitErrorMessage {
  return (
    typeof msg === 'object' &&
    msg !== null &&
    'type' in msg &&
    (msg as WorkerInitErrorMessage).type === 'init-error'
  );
}

/**
 * Type guard to check if a message is a response (has correlation id).
 */
export function isResponse(msg: unknown): msg is WorkerResponse {
  return (
    typeof msg === 'object' &&
    msg !== null &&
    'id' in msg &&
    'success' in msg &&
    typeof (msg as WorkerResponse).id === 'string' &&
    typeof (msg as WorkerResponse).success === 'boolean'
  );
}

/**
 * Type guard to narrow a response to success case.
 */
export function isSuccessResponse<T>(
  response: WorkerResponse<T>
): response is WorkerSuccessResponse<T> {
  return response.success === true;
}

/**
 * Type guard to narrow a response to error case.
 */
export function isErrorResponse(
  response: WorkerResponse
): response is WorkerErrorResponse {
  return response.success === false;
}

// ---------------------------------------------------------------------------
// Helper Types
// ---------------------------------------------------------------------------

/**
 * Extract the payload type for a given request type.
 * Usage: PayloadFor<'card:create'> → { input: CardInput }
 */
export type PayloadFor<T extends WorkerRequestType> = WorkerPayloads[T];

/**
 * Extract the response data type for a given request type.
 * Usage: ResponseFor<'card:create'> → Card
 */
export type ResponseFor<T extends WorkerRequestType> = WorkerResponses[T];

/**
 * Pending request tracker used internally by WorkerBridge.
 * Maps correlation ID to promise resolution callbacks.
 */
export interface PendingRequest<T = unknown> {
  resolve: (value: T) => void;
  reject: (error: Error) => void;
  timeoutId: ReturnType<typeof setTimeout>;
  /** Request type — for debugging/logging */
  type: WorkerRequestType;
  /** Timestamp when request was sent — for latency tracking */
  sentAt: number;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * WorkerBridge configuration options.
 */
export interface WorkerBridgeConfig {
  /**
   * Timeout in milliseconds for each request.
   * If exceeded, promise rejects with TIMEOUT error.
   * @default 30000 (30 seconds)
   */
  timeout?: number;

  /**
   * Enable development mode logging.
   * Logs request/response timing and correlation IDs.
   * @default false
   */
  debug?: boolean;
}

/**
 * Default configuration values.
 */
export const DEFAULT_WORKER_CONFIG: Required<WorkerBridgeConfig> = {
  timeout: 30_000,
  debug: false,
};
