import { render, screen, fireEvent } from '@testing-library/react';
import { SuperAudit, CellState, AuditMode } from '../SuperAudit';
import { vi } from 'vitest';

describe('SuperAudit', () => {
  const mockOnModeChange = vi.fn();
  const mockOnHighlightComputed = vi.fn();

  const sampleCellStates: CellState[] = [
    { id: 'cell1', type: 'raw', value: 'Project Alpha', lastModified: new Date().toISOString() },
    { id: 'cell2', type: 'computed', value: '=SUM(Q1)', formula: '=SUM(Q1)', lastModified: new Date().toISOString() },
    { id: 'cell3', type: 'enriched', value: 'Generated by ETL', source: 'ETL Pipeline', lastModified: new Date().toISOString() },
    { id: 'cell4', type: 'crud_modified', value: 'Updated Project', crudOperation: 'UPDATE', lastModified: new Date().toISOString() }
  ];

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Basic Rendering', () => {
    it('should render audit toggle button', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="off"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(screen.getByRole('button', { name: /toggle audit mode/i })).toBeInTheDocument();
      expect(screen.getByText(/audit mode: off/i)).toBeInTheDocument();
    });

    it('should show cell statistics when in audit mode', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(screen.getByText(/audit mode: highlight/i)).toBeInTheDocument();
      expect(screen.getByText(/4 cells tracked/i)).toBeInTheDocument();
    });
  });

  describe('Mode Switching', () => {
    it('should cycle through audit modes when clicked', () => {
      const { rerender } = render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="off"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      const toggleButton = screen.getByRole('button', { name: /toggle audit mode/i });

      fireEvent.click(toggleButton);
      expect(mockOnModeChange).toHaveBeenCalledWith('highlight');

      // Mock mode change to 'highlight' and re-render
      mockOnModeChange.mockClear();
      rerender(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      fireEvent.click(screen.getByRole('button', { name: /toggle audit mode/i }));
      expect(mockOnModeChange).toHaveBeenCalledWith('formulas');
    });

    it('should call onHighlightComputed when entering highlight mode', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(mockOnHighlightComputed).toHaveBeenCalledWith(['cell2', 'cell3', 'cell4']);
    });
  });

  describe('Cell State Breakdown', () => {
    it('should show detailed breakdown in formulas mode', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="formulas"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(screen.getByText(/cell analysis/i)).toBeInTheDocument();
      // Check the statistics breakdown exists with correct structure
      expect(screen.getByText('Raw Data')).toBeInTheDocument();
      expect(screen.getAllByText(/computed/i)).toHaveLength(2); // One in stats, one in section header
      expect(screen.getByText('Enriched')).toBeInTheDocument();
      expect(screen.getByText('Modified')).toBeInTheDocument();
    });

    it('should show formula details for computed cells', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="formulas"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(screen.getByText(/computed cells/i)).toBeInTheDocument();
      expect(screen.getByText('=SUM(Q1)')).toBeInTheDocument();
    });
  });

  describe('Visual Indicators', () => {
    it('should provide correct CSS classes for different cell types', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      // Test that legend items are present with appropriate structure
      expect(screen.getByText('1 computed')).toBeInTheDocument();
      expect(screen.getByText('1 enriched')).toBeInTheDocument();
      expect(screen.getByText('1 modified')).toBeInTheDocument();
    });

    it('should show CRUD operation indicators', () => {
      const recentCrudCells: CellState[] = [
        { id: 'crud1', type: 'crud_created', value: 'New Card', crudOperation: 'CREATE', lastModified: new Date().toISOString() },
        { id: 'crud2', type: 'crud_deleted', value: 'Deleted Card', crudOperation: 'DELETE', lastModified: new Date().toISOString() }
      ];

      render(
        <SuperAudit
          cellStates={recentCrudCells}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      expect(screen.getByText(/2 cells tracked/i)).toBeInTheDocument();
    });
  });

  describe('Performance Metrics', () => {
    it('should handle large numbers of cell states efficiently', () => {
      const largeCellStates: CellState[] = Array.from({ length: 1000 }, (_, i) => ({
        id: `cell${i}`,
        type: i % 4 === 0 ? 'computed' : 'raw',
        value: `Cell ${i}`,
        lastModified: new Date().toISOString()
      }));

      const start = performance.now();
      render(
        <SuperAudit
          cellStates={largeCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );
      const end = performance.now();

      expect(end - start).toBeLessThan(100); // Should render in < 100ms
      expect(screen.getByText(/1000 cells tracked/i)).toBeInTheDocument();
    });
  });

  describe('Accessibility', () => {
    it('should provide proper ARIA labels and keyboard navigation', () => {
      render(
        <SuperAudit
          cellStates={sampleCellStates}
          currentMode="highlight"
          onModeChange={mockOnModeChange}
          onHighlightComputed={mockOnHighlightComputed}
        />
      );

      const toggleButton = screen.getByRole('button', { name: /toggle audit mode/i });
      expect(toggleButton).toHaveAttribute('aria-label');
      expect(toggleButton).toHaveAttribute('title');
    });
  });
});